##
# Configure auditd on the target system.
#
# 
# Initially written by a Tired Matthew Harper
##

---
- name: Auditd-Configuration
  hosts: inventory # Need to Coordinate This
  become: true # Need to be sudo
  vars:
    conf_file_trgt: /etc/audit/rules.d/ccdc.rules
    conf_name: ./audit_rules.conf # Change to something else if wanted
  tasks:
    - name: Configure-Forward-Journald
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '.*ForwardToSyslog.*'
        line: 'ForwardToSyslog yes'
    - name: Configure-Compress-Journald
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '.*Compress.*'
        line: 'Compress=yes'
    - name: Configure-DiskWrite-Journald
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '.*Storage.*'
        line: 'Storage=persistent'
