##
# Usage: Initial SSH configuration of Target Linux Machines.
#
# The goal of this script is to provide a secure initial configuration and one that is "Safe" i.e maintains
# uptime and access to the target system. A number of the suggestions are over the top, but are from Wazuh...
#
# Initially written by a Tired Matthew Harper
# Based on:
# * https://github.com/UML-Cyber-Security/ccdc2024/blob/main/2-Scripts/SOC/AnsibleMisc_WazuhSurricataSSH/03sshHardening/hardenSSH.yml -- not where it should have been :(
# * https://github.com/UML-Cyber-Security/ccdc2024/blob/main/2-Scripts/Ansible/Linux/Account-Management/pubkey-enforcement-copy-sshkeys.yml
# * https://github.com/UML-Cyber-Security/ccdc2024/tree/main/2-Scripts/Linux/Files-Services-configs/SSH
#
# NOTE: Will create a backup file named sshd_config.bak
##

---
- name: SSH-Inital-Harden
  hosts: inventory # Need to Coordinate This
  become: true # Need to be sudo
  tasks: 
    - name: Backup-SSHD-File
      ansible.builtin.copy:
        remote_src: true 
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.bak
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Create-SSHD-Backup-Directory
      ansible.builtin.file:
        path: /etc/ssh/sshd_config_bak.d
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx

    - name: Backup-SSD-Directory
      ansible.builtin.copy:
        remote_src: true
        src: /etc/ssh/sshd_config.d
        dest: /etc/ssh/sshd_config_bak.d
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx

    - name: configure-Root-Login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*PermitRootLogin.*'
        line: 'PermitRootLogin no'

    - name: configure-Protocol-Version
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*Protocol.*'
        line: 'Protocol 2'

    - name: configure-Logging
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*LogLevel.*'
        line: 'LogLevel VERBOSE'

    - name: configure-Max-Auth
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*MaxAuthTries.*'
        line: 'MaxAuthTries 4'

    - name: configure-Rhost-Ignore
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*IgnoreRhosts.*'
        line: 'IgnoreRhosts yes'

    - name: configure-Host-Ignore
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*HostBasedAuthentication.*'
        line: 'HostBasedAuthentication no'

    - name: configure-Permit-User-Env
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*PermitUserEnvironment.*'
        line: 'PermitUserEnvironment no'

    - name: configure-Disable-Empty-Pass
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*PermitEmptyPasswords.*'
        line: 'PermitEmptyPasswords no'

    - name: configure-Client-Alive
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*ClientAliveInterval .*'
        line: 'ClientAliveInterval 300'

    - name: configure-Client-Alive-Max
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*ClientAliveCountMax .*'
        line: 'ClientAliveCountMax 0'

    - name: configure-Client-Login-Grace
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*LoginGraceTime .*'
        line: 'LoginGraceTime 60'

    - name: configure-Max-Startup
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*MaxStartups .*'
        line: 'MaxStartups 10:30:60'

    - name: configure-Max-Session
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*MaxSessions .*'
        line: 'MaxSessions 10'

    - name: configure-Ciphers
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*Ciphers .*'
        line: 'Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'

    - name: configure-MACs
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*MACs .*'
        line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256'

    - name: configure-KEX
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*KexAlgorithms .*'
        line: 'KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256'
      notify:
        - Restart-SSHD
  handlers:
    - name: Restart-SSHD
      systemd:
        name: sshd
        state: restarted




...
