##
# Usage: Configure SSH to prevent forwarding
#
# The goal of this script is to provide a secure initial configuration and one that is "Safe" i.e maintains
# uptime and access to the target system. A number of the suggestions are over the top, but are from Wazuh...
#
# Initially written by a Tired Matthew Harper
# Based on:
# * https://github.com/UML-Cyber-Security/ccdc2024/blob/main/2-Scripts/SOC/AnsibleMisc_WazuhSurricataSSH/03sshHardening/hardenSSH.yml -- not where it should have been :(
# * https://github.com/UML-Cyber-Security/ccdc2024/blob/main/2-Scripts/Ansible/Linux/Account-Management/pubkey-enforcement-copy-sshkeys.yml
# * https://github.com/UML-Cyber-Security/ccdc2024/tree/main/2-Scripts/Linux/Files-Services-configs/SSH
#
# NOTE: Will create a backup file named sshd_config.bak
##

---
- name: SSH-Inital-Harden
  hosts: inventory # Need to Coordinate This
  become: true # Need to be sudo
  tasks: 
    - name: Backup-SSHD-File
      ansible.builtin.copy:
        remote_src: true 
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config_danger.bak
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Create-SSHD-Backup-Directory
      ansible.builtin.file:
        path: /etc/ssh/sshd_config_bak_danger.d
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx

    - name: Backup-SSD-Directory
      ansible.builtin.copy:
        remote_src: true
        src: /etc/ssh/sshd_config.d
        dest: /etc/ssh/sshd_config_bak_danger.d
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx

    - name: disable-tcp-forwarding
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*AllowTcpForwarding.*'
        line: 'AllowTcpForwarding no'

    - name: disable-x11-forwarding
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*X11Forwarding.*'
        line: 'X11Forwarding no'
      notify:
        - Restart-SSHD
  handlers:
    - name: Restart-SSHD
      systemd:
        name: sshd
        state: restarted






